### ISSUE TITLE
Malformed http request 

### ISSUE THREAD

**Issue by Oloremo** [github/vulcanizer#54]
Hi!
Each command that I try looks like adding strange double slash symbols `//`
```
vulcanizer -f conf/vulcanizer.yaml -c local settings
Error getting settings: Bad HTTP Status from Elasticsearch: 400, No handler found for uri [///_cluster/settings] and method [GET]
```

My config:
```
conf/vulcanizer.yaml
local:
  host: "test-run-kproskurin-01"
  port: 9200
```

Am I doing something wrong?
